"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { Footer, Header } from './components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Infinity',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  
  return (
    <html>
      <body>
      <main className={inter.className}>
      <Header />
        {children}
      <Footer />
        </main>
      </body>
    </html>
  )
}
